/* Generated By:JJTree: Do not edit this line. ASTaxis_statement_def.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.mdx.parser;

public
class ASTaxis_statement_def extends SimpleNode {
  public ASTaxis_statement_def(int id) {
    super(id);
  }

  public ASTaxis_statement_def(WormholeMDXParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WormholeMDXParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=00f52e5605a25f0f92b05bf4f2f74e96 (do not edit this line) */
