/* Generated By:JJTree: Do not edit this line. ASTaxis_alias.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.mdx.parser;

public
class ASTaxis_alias extends SimpleNode {
  public ASTaxis_alias(int id) {
    super(id);
  }

  public ASTaxis_alias(WormholeMDXParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WormholeMDXParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2dbe0c6d6a172722ca0b7f23a5cc5ffa (do not edit this line) */
