/* Generated By:JJTree: Do not edit this line. ASTbuild_statement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.mdx.parser;

public
class ASTbuild_statement extends SimpleNode {
  public ASTbuild_statement(int id) {
    super(id);
  }

  public ASTbuild_statement(WormholeMDXParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WormholeMDXParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a4fbb80f3f2bf6d9f9b06d32bc8f02e5 (do not edit this line) */
