/* Generated By:JJTree: Do not edit this line. ASTCUD_measure_stat_V.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.mdx.parser;

public
class ASTCUD_measure_stat_V extends SimpleNode {
  public ASTCUD_measure_stat_V(int id) {
    super(id);
  }

  public ASTCUD_measure_stat_V(WormholeMDXParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WormholeMDXParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=622a989a1799ab497e2947f82a64bfe8 (do not edit this line) */
