/* Generated By:JJTree: Do not edit this line. ASTcreate_dimension_statement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.mdx.parser;

public
class ASTcreate_dimension_statement extends SimpleNode {
  public ASTcreate_dimension_statement(int id) {
    super(id);
  }

  public ASTcreate_dimension_statement(WormholeMDXParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WormholeMDXParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ce1e1a4cc8d70908595167527df5ee55 (do not edit this line) */
