/* Generated By:JJTree: Do not edit this line. ASTdomain_selector_part.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.mdx.parser;

public
class ASTdomain_selector_part extends SimpleNode {
  public ASTdomain_selector_part(int id) {
    super(id);
  }

  public ASTdomain_selector_part(WormholeMDXParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WormholeMDXParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=06a1829ddc104332300b165cb329eed9 (do not edit this line) */
