/* Generated By:JJTree: Do not edit this line. ASTint_upt_del_measure_statement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.mdx.parser;

public
class ASTint_upt_del_measure_statement extends SimpleNode {
  public ASTint_upt_del_measure_statement(int id) {
    super(id);
  }

  public ASTint_upt_del_measure_statement(WormholeMDXParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WormholeMDXParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8058d6751c868dfde80ed8935a7803cf (do not edit this line) */
