/* Generated By:JJTree: Do not edit this line. ASTmulti_dimensional_domain_select.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.mdx.parser;

public
class ASTmulti_dimensional_domain_select extends SimpleNode {
  public ASTmulti_dimensional_domain_select(int id) {
    super(id);
  }

  public ASTmulti_dimensional_domain_select(WormholeMDXParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WormholeMDXParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=09e8267af735dc6dfbb59a8a2762c0fb (do not edit this line) */
