/* Generated By:JJTree: Do not edit this line. ASTwhere_statement_def.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.mdx.parser;

public
class ASTwhere_statement_def extends SimpleNode {
  public ASTwhere_statement_def(int id) {
    super(id);
  }

  public ASTwhere_statement_def(WormholeMDXParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WormholeMDXParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=58cb8d0551f8a9e7402e4427d9eff5a1 (do not edit this line) */
