/* Generated By:JavaCC: Do not edit this line. WormholeMDXParserTreeConstants.java Version 6.0_1 */
package cn.bgotech.wormhole.olap.mdx.parser;

public interface WormholeMDXParserTreeConstants
{
  public int JJTEXECUTE = 0;
  public int JJTAUXILIARY_MDDL_NQ_STATEMENT = 1;
  public int JJTCREATE_DIMENSION_STATEMENT = 2;
  public int JJTCREATE_MEMBER_STATEMENT = 3;
  public int JJTBUILD_CUBE_STATEMENT = 4;
  public int JJTSYNC_CUBE_STATEMENT = 5;
  public int JJTWRITEBACK_CUBE_STATEMENT = 6;
  public int JJTINT_UPT_DEL_MEASURE_STATEMENT = 7;
  public int JJTCUD_MEASURE_STAT_V = 8;
  public int JJTLOAD_CUBE_DATA_STATEMENT = 9;
  public int JJTCREATE_STATEMENT = 10;
  public int JJTLOADCUBEDATA_STATEMENT = 11;
  public int JJTBUILD_STATEMENT = 12;
  public int JJTINSERT_STATEMENT = 13;
  public int JJTUPDATE_STATEMENT = 14;
  public int JJTDELETE_STATEMENT = 15;
  public int JJTSELECT_STATEMENT = 16;
  public int JJTWITH_STATEMENT_DEF = 17;
  public int JJTSET_FORMULA_STATEMENT = 18;
  public int JJTMEMBER_FORMULA_STATEMENT = 19;
  public int JJTEXPRESSION = 20;
  public int JJTTERM = 21;
  public int JJTFACTORY = 22;
  public int JJTCOMMON_FUNCTIONS = 23;
  public int JJTSET = 24;
  public int JJTSET_FUNCTIONS = 25;
  public int JJTDESCENDANTS_OPTIONS = 26;
  public int JJTBOOLEAN_EXPRESSION = 27;
  public int JJTBOOLEAN_TERM = 28;
  public int JJTBOOLEAN_FACTORY = 29;
  public int JJTBOOLEAN_FUNCTION = 30;
  public int JJTLEVEL = 31;
  public int JJTTUPLE = 32;
  public int JJTMEMBER = 33;
  public int JJTMEMBER_FUNCTIONS = 34;
  public int JJTDIMENSION = 35;
  public int JJTAXIS_STATEMENT_DEF = 36;
  public int JJTAXIS_ALIAS = 37;
  public int JJTWHERE_STATEMENT_DEF = 38;
  public int JJTCUBE = 39;
  public int JJTMULTI_DIMENSIONAL_DOMAIN_SELECT = 40;
  public int JJTDOMAIN_SELECTOR_PART = 41;
  public int JJTSIGNED_DOUBLE_STATEMENT = 42;


  public String[] jjtNodeName = {
    "execute",
    "auxiliary_MDDL_NQ_statement",
    "create_dimension_statement",
    "create_member_statement",
    "build_cube_statement",
    "sync_cube_statement",
    "writeback_cube_statement",
    "int_upt_del_measure_statement",
    "CUD_measure_stat_V",
    "load_cube_data_statement",
    "create_statement",
    "loadCubeData_statement",
    "build_statement",
    "insert_statement",
    "update_statement",
    "delete_statement",
    "select_statement",
    "with_statement_def",
    "set_formula_statement",
    "member_formula_statement",
    "expression",
    "term",
    "factory",
    "common_functions",
    "set",
    "set_functions",
    "descendants_options",
    "boolean_expression",
    "boolean_term",
    "boolean_factory",
    "boolean_function",
    "level",
    "tuple",
    "member",
    "member_functions",
    "dimension",
    "axis_statement_def",
    "axis_alias",
    "where_statement_def",
    "cube",
    "multi_dimensional_domain_select",
    "domain_selector_part",
    "signed_double_statement",
  };
}
/* JavaCC - OriginalChecksum=7ce89d386246c39bcff64a9ada4335ae (do not edit this line) */
