/* Generated By:JJTree: Do not edit this line. ASTparserEntry.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.imp.text.parser;

public
class ASTparserEntry extends SimpleNode {
  public ASTparserEntry(int id) {
    super(id);
  }

  public ASTparserEntry(TextFormatCubeParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TextFormatCubeParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eccbc74c97dcabbcffda6349043ab231 (do not edit this line) */
