/* Generated By:JJTree&JavaCC: Do not edit this line. TextFormatCubeParserConstants.java */
package cn.bgotech.wormhole.olap.imp.text.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TextFormatCubeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int SIMPLE_NUMERIC = 7;
  /** RegularExpression Id. */
  int DIMENSION = 8;
  /** RegularExpression Id. */
  int PRE_DIMENSION = 9;
  /** RegularExpression Id. */
  int DIMENSION_ROLE = 10;
  /** RegularExpression Id. */
  int MEASURE = 11;
  /** RegularExpression Id. */
  int MEMBER = 12;
  /** RegularExpression Id. */
  int VALUE = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<DIGIT>",
    "<SIMPLE_NUMERIC>",
    "<DIMENSION>",
    "<PRE_DIMENSION>",
    "<DIMENSION_ROLE>",
    "<MEASURE>",
    "<MEMBER>",
    "<VALUE>",
  };

}
