/* Generated By:JavaCC: Do not edit this line. TextFormatCubeParserVisitor.java Version 6.0_1 */
package cn.bgotech.wormhole.olap.imp.text.parser;

public interface TextFormatCubeParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTparserEntry node, Object data);
}
/* JavaCC - OriginalChecksum=cdd21b99b0fe48cd1ea76d7c57262444 (do not edit this line) */
