/* Generated By:JavaCC: Do not edit this line. TextFormatCubeParserTreeConstants.java Version 6.0_1 */
package cn.bgotech.wormhole.olap.imp.text.parser;

public interface TextFormatCubeParserTreeConstants
{
  public int JJTPARSERENTRY = 0;


  public String[] jjtNodeName = {
    "parserEntry",
  };
}
/* JavaCC - OriginalChecksum=eaabf1432fc9b85850eb8cfb895a1498 (do not edit this line) */
