/* Generated By:JavaCC: Do not edit this line. TextFormatCubeParserDefaultVisitor.java Version 6.0_1 */
package cn.bgotech.wormhole.olap.imp.text.parser;

public class TextFormatCubeParserDefaultVisitor implements TextFormatCubeParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTparserEntry node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=7d269a845faf4979a7f2c0b5bc5c1a41 (do not edit this line) */
