/* Generated By:JJTree: Do not edit this line. ASTcolumnDefinition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.util.db.design.parser;

public
class ASTcolumnDefinition extends SimpleNode {
  public ASTcolumnDefinition(int id) {
    super(id);
  }

  public ASTcolumnDefinition(DatabaseModelDefinition2DDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DatabaseModelDefinition2DDLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=061a9a5172dd83a12584e3e392084d7e (do not edit this line) */
