/* Generated By:JJTree: Do not edit this line. ASTparserEntry.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.util.db.design.parser;

public
class ASTparserEntry extends SimpleNode {
  public ASTparserEntry(int id) {
    super(id);
  }

  public ASTparserEntry(DatabaseModelDefinition2DDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DatabaseModelDefinition2DDLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=08b59c3465fa413a7122e04edc523225 (do not edit this line) */
