/* Generated By:JJTree: Do not edit this line. ASTtableDefinition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.bgotech.wormhole.olap.util.db.design.parser;

public
class ASTtableDefinition extends SimpleNode {
  public ASTtableDefinition(int id) {
    super(id);
  }

  public ASTtableDefinition(DatabaseModelDefinition2DDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DatabaseModelDefinition2DDLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c2b7076161a9b96782ead4272d86debc (do not edit this line) */
