/* Generated By:JavaCC: Do not edit this line. DatabaseModelDefinition2DDLParserTreeConstants.java Version 6.0_1 */
package cn.bgotech.wormhole.olap.util.db.design.parser;

public interface DatabaseModelDefinition2DDLParserTreeConstants
{
  public int JJTPARSERENTRY = 0;
  public int JJTTABLEDEFINITION = 1;
  public int JJTCOLUMNDEFINITION = 2;


  public String[] jjtNodeName = {
    "parserEntry",
    "tableDefinition",
    "columnDefinition",
  };
}
/* JavaCC - OriginalChecksum=606358fc2e25c5d9120101fe4b611b23 (do not edit this line) */
