/* Generated By:JavaCC: Do not edit this line. DatabaseModelDefinition2DDLParserVisitor.java Version 6.0_1 */
package cn.bgotech.wormhole.olap.util.db.design.parser;

public interface DatabaseModelDefinition2DDLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTparserEntry node, Object data);
  public Object visit(ASTtableDefinition node, Object data);
  public Object visit(ASTcolumnDefinition node, Object data);
}
/* JavaCC - OriginalChecksum=872a84273d6ec6eaf5875db6e118c6fe (do not edit this line) */
