/* Generated By:JJTree&JavaCC: Do not edit this line. DatabaseModelDefinition2DDLParserConstants.java */
package cn.bgotech.wormhole.olap.util.db.design.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DatabaseModelDefinition2DDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int LETTER = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int DB_TYPE_PREFIX = 10;
  /** RegularExpression Id. */
  int DB_OBJ = 11;
  /** RegularExpression Id. */
  int DEFAULT_VALUE = 12;
  /** RegularExpression Id. */
  int ABSTRACT_TABLE_PREFIX = 13;
  /** RegularExpression Id. */
  int TABLE_PREFIX = 14;
  /** RegularExpression Id. */
  int NO_NULL = 15;
  /** RegularExpression Id. */
  int UNIQUE = 16;
  /** RegularExpression Id. */
  int PK = 17;
  /** RegularExpression Id. */
  int FK_PREFIX = 18;
  /** RegularExpression Id. */
  int DESC = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<DIGIT>",
    "<LETTER>",
    "<INT>",
    "\"[database:\"",
    "<DB_OBJ>",
    "<DEFAULT_VALUE>",
    "\"[AT:\"",
    "\"[T:\"",
    "\"[nonull]\"",
    "\"[unique]\"",
    "\"[pk]\"",
    "\"[FK:\"",
    "<DESC>",
    "\"]\"",
    "\"-\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"<pk>\"",
    "\"<pK>\"",
    "\"<Pk>\"",
    "\"<PK>\"",
  };

}
