/* Generated By:JavaCC: Do not edit this line. DatabaseModelDefinition2DDLParserDefaultVisitor.java Version 6.0_1 */
package cn.bgotech.wormhole.olap.util.db.design.parser;

public class DatabaseModelDefinition2DDLParserDefaultVisitor implements DatabaseModelDefinition2DDLParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTparserEntry node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTtableDefinition node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTcolumnDefinition node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=9908f59656212db11c61175b843e8345 (do not edit this line) */
